import Head from "next/head";
import { getCharacterDetails } from "../services";
import { PostCard } from "../components";

export default function Home({ data }) {
  console.log(data);
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="postcard">
        {data.map((char, index) => (
          <PostCard data={char} key={index} />
        ))}
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const characterData = (await getCharacterDetails()) || [];

  return {
    props: { data: characterData },
  };
};
